version: '3'
services:
  db:
    image: postgres:16
    command: -p 5432
    expose:
      - 5432
    ports:
      - $POSTGRES_PORT:5432
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
  redis:
    image: redis:7
    ports:
      - $REDIS_PORT:6379
  app:
    build: .
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    env_file: .env
    expose:
      - 8000
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
