version: '3'
services:
  db:
    image: postgres:16
    container_name: db
    command: -p 5432
    expose:
      - 5432
    env_file:
      - .env
    ports:
      - $POSTGRES_PORT:5432
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB

  redis:
    image: redis:7
    container_name: redis
    command: --port 6379
    expose:
      - 6379
    env_file:
      - .env
    ports:
      - $REDIS_PORT:6379

  app:
    build:
      context: .
    env_file:
      - .env
    container_name: django_app
    command: sh -c "python manage.py migrate && python manage.py createsuperuser --noinput  && python manage.py runserver 0.0.0.0:8000"

    expose:
      - 8000
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis

  celery:
    build:
      context: .
    env_file:
      - .env
    container_name: celery
    command: sh -c "celery -A config worker -l INFO"
    depends_on:
      - redis

  flower:
    build:
      context: .
    env_file:
      - .env
    container_name: flower
    command: sh -c "celery -A config flower"
    depends_on:
      - redis
      - celery
    ports:
      - 8888:5555
