# Generated by Django 5.0.1 on 2024-02-09 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auction", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="auction",
            old_name="base_price",
            new_name="current_price",
        ),
        migrations.AlterField(
            model_name="auction",
            name="auction_status",
            field=models.IntegerField(
                choices=[(0, "Pending"), (1, "In Progress"), (2, "Closed")], default=0
            ),
        ),
    ]
